ecomm/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
import registration.urls
import products.urls
import orders.urls
import pages.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include(registration.urls)),
    url(r'^product/', include(products.urls)),
    url(r'^orders/', include(orders.urls, namespace='orders')),
    url(r'^', include(pages.urls, namespace='pages')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.handle_404_view'

ecomm/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^order$', views.order, name='order'),
    url(r'^order/(?P<order_id>[0-9]+)$', views.view_order, name='view-order'),
    url(r'^myorders$', views.get_my_orders, name='my-orders'),
]

ecomm/pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^contact-success/$', views.contact_success, name='contact-success'),
]

ecomm/templates/base.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}SeeChic{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="{% static 'lib/css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/css/memenu.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <link href='//fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
    {% block css %}{% endblock %}
</head>
<body>
<!--header-->
<div class="header">
    <div class="header-top">
        <div class="container">
            <div class="social">
                <ul>
                    <li>
                        <a href="https://www.facebook.com/SeeChic-432499216938827/">
                            <i class="facebok"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/seechic/">
                            <i class="inst"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="header-left">
                <div class="ca-r">
                    {% if user.is_authenticated %}
                    <h5>Welcome {{user.username}}</h5>
                    {% endif %}
                    <div class="cart box_1">
                        <a href="{% url 'orders:checkout' %}">
                            <h3>
                                <div class="total">
                                    <span class="simpleCart_total"></span>
                                </div>
                                <img src="{% static 'images/cart.png' %}" alt=""/>
                            </h3>
                        </a>

                        <p>
                            <a href="javascript:;" class="simpleCart_empty">Empty Cart</a>
                        </p>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="head-top">
            <div class="logo">
                <h1><a href="{% url 'pages:index' %}">SeeChic</a></h1>
            </div>
            <div class="h_menu4">
                <ul class="memenu skyblue">
                    <li><a class="color6" href="{% url 'pages:index' %}">Home</a></li>
                    <li><a class="color1" href="#">Categories</a>

                        <div class="mepanel">
                            <div class="row">
                                {% for category_part in categories %}
                                <div class="col1">
                                    <div class="h_nav">
                                        <ul>
                                            {% for category in category_part %}
                                            <li>
                                                <a href="{% url 'category_detail' category.id category.slug%}">
                                                    {{category.name}}
                                                </a>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                    {% if user.is_authenticated %}
                    <li><a class="color4" href="{% url 'orders:my-orders' %}">My Orders</a></li>
                    <li><a class="color4" href="{% url 'logout' %}">Logout</a></li>
                    <li><a class="color4" href="{% url 'password_change' %}">Change Password</a></li>
                    {% else %}
                    <li><a class="color4" href="{% url 'login' %}">Login</a></li>
                    <li><a class="color4" href="{% url 'register' %}">Register</a></li>
                    {% endif %}
                    <li><a class="color6" href="{% url 'pages:contact' %}">Contact</a></li>
                </ul>
            </div>

            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% block content%}
{% endblock %}
<div class="footer">
    <div class="container">
        <div class="footer-top-at">
            <div class="col-md-4 amet-sed">
                <h4>CATEGORIES</h4>
                <ul class="nav-bottom">
                    {% for category in categories.0|slice:":6" %}
                    <li>
                        <a href="{% url 'category_detail' category.id category.slug %}">
                            {{category.name}}
                        </a>
                    </li>
                    {% endfor %}
                </ul>

            </div>
            <div class="col-md-4 amet-sed">
                <h4>CONTACT US</h4>

                <p>
                    Call us: +65 3163 2052<br/>
                    Opening hours:<br/>
                    Mon-Fri 9am to 6pm
                </p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="footer-class">
        <p>© 2016 SeeChic . All Rights Reserved |
            Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a></p>
    </div>
</div>
<script src="{% static 'lib/js/jquery.min.js' %}"></script>
<script src="{% static 'lib/js/memenu.js' %}"></script>
<script src="{% static 'lib/js/simpleCart.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>