ecomm/pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^contact-success/$', views.contact_success, name='contact-success'),
]

ecomm/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<product_id>[0-9]+)/([-\w\d\_]+)/$', views.product_detail, name='product_detail'),
    url(r'^cat/(?P<category_id>[0-9]+)/([-\w\d\_]+)/$', views.category_detail, name='category_detail'),
]

ecomm/products/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from autoslug import AutoSlugField


@python_2_unicode_compatible
class ProductCategory(models.Model):
    name = models.CharField(_('name'), max_length=255)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def get_absolute_url(self):
        return "product:category_detail", [self.slug]

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Product(models.Model):
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_('description'))
    price = models.FloatField(_('price'))
    category_id = models.ForeignKey(ProductCategory, verbose_name=_('category'))
    slug = AutoSlugField(populate_from='name')
    is_featured = models.BooleanField(verbose_name=_('Featured?'), default=False)

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def get_absolute_url(self):
        return "product:product_detail", [self.slug]

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to='products/', verbose_name=_("Image"))

ecomm/products/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory


def product_detail(request, product_id, *args):
    product = get_object_or_404(Product, pk=product_id)
    context = {'product': product}
    return render(request, "products/product_detail.html", context)


def category_detail(request, category_id, *args):
    category = get_object_or_404(ProductCategory, pk=category_id)
    products_list = category.product_set.all()
    paginator = Paginator(products_list, 10)
    page = request.GET.get('page')
    try:
        products_list = paginator.page(page)
    except PageNotAnInteger:
        products_list = paginator.page(1)
    except EmptyPage:
        products_list = paginator.page(paginator.num_pages)
    context = {
        'category_name': category.name,
        'products': products_list,
        'pages': range(1, paginator.num_pages + 1)
    }
    return render(request, "products/category_detail.html", context)

ecomm/products/templates/products/category_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{%block title%}{{site_name}} - {{category_name}}{%endblock%}
{%block content%}
<!-- grow -->
<div class="grow">
    <div class="container">
        <h2>{{category_name}}</h2>
    </div>
</div>
<!-- grow -->
<div class="pro-du">
    <div class="container">
        {% if products %}
        <div class="col-md-9 product1">
            <div class="bottom-product">
                {% for product in products|slice:":4"%}
                <div class="col-md-6 bottom-cd simpleCart_shelfItem">
                    <div class="product-at">
                        <a href="{% url 'product_detail' product.id product.slug %}">
                            <img class="img-responsive item_image" src="{{product.productimage_set.all.0.image.url}}"
                                 alt="{{product.name}}">

                            <div class="pro-grid">
                                <span class="buy-in">Buy Now</span>
                            </div>
                        </a>
                    </div>
                    <p class="tun"><span class="item_name">{{product.name}}</span><br>{{category_name}}</p>

                    <div class="ca-rt">
                        <span class="hidden item_id">{{product.id}}</span>
                        <a href="#" class="item_add">
                            <p class="number item_price"><i> </i>${{product.price}}</p>
                        </a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                {% endfor %}
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-md-3 prod-rgt">
            {% for product in products|slice:"4:" %}
            <div class=" pro-tp">
                <div class="pl-lft">
                    <a href="{% url 'product_detail' product.id product.slug %}">
                        <img class="img-responsive" src="{{product.productimage_set.all.0.image.url}}"
                             alt="{{product.name}}">
                    </a>
                </div>
                <div class="pl-rgt">
                    <h6>
                        <a href="{% url 'product_detail' product.id product.slug %}">
                            {{product.name}}
                        </a>
                    </h6>

                    <p><a href="{% url 'product_detail' product.id product.slug %}">${{product.price}}</a></p>
                </div>
                <div class="clearfix"></div>
            </div>
            {% endfor %}
        </div>
        <div class="clearfix"></div>

        <div class="pagination center-block">
            <ul class="pagination pagination-lg">
                {% for page in pages %}
                <li><a href="?page={{ page }}">{{page}}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% else %}
            <br/><h3>This category haven't any products yet.</h3><br/>
        {% endif %}
    </div>
</div>
<!-- products -->
{% endblock %}
{% block script%}
<script src="{% static 'products/lib/js/imagezoom.js'%}"></script>
<script src="{% static 'products/lib/js/jquery.flexslider.js'%}"></script>
<script src="{% static 'products/js/script.js'%}"></script>
{%endblock%}

ecomm/products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{%block title%}{{site_name}} - {{product.name}}{%endblock%}
{% block css %}
<link rel="stylesheet" href="{% static 'products/lib/css/flexslider.css'%}"/>
{% endblock %}
{%block content%}
<!-- grow -->
<div class="grow">
    <div class="container">
        <h2>{{product.name}}</h2>
    </div>
</div>
<!-- grow -->
<div class="product">
    <div class="container">

        <div class="product-price1">
            <div class="top-sing">
                <div class="col-md-7 single-top">
                    <div class="flexslider">
                        <ul class="slides">
                            {% for obj in product.productimage_set.all %}
                            <li data-thumb="{{obj.image.url}}">
                                <div class="thumb-image">
                                    <img src="{{obj.image.url}}" data-imagezoom="true" class="img-responsive">
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-md-5 single-top-in simpleCart_shelfItem">
                    <div class="single-para ">
                        <h4 class="item_name">{{product.name}}</h4>
                        <h4 class="item_id hidden">{{product.id}}</h4>
                        <span class="hidden item_image">{{product.productimage_set.all.0.image.url}}</span>
                        <h5 class="item_price">{{product.price}}</h5>

                        <p>{{product.description}}</p>

                        <a href="#" class="add-cart item_add">ADD TO CART</a>

                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
</div>
{% endblock %}
{% block script%}
<script src="{% static 'products/lib/js/imagezoom.js'%}"></script>
<script src="{% static 'products/lib/js/jquery.flexslider.js'%}"></script>
<script src="{% static 'products/js/script.js'%}"></script>
{%endblock%}